name: CI

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22
                cache: 'npm'
            - name: Install deps(client and server via root scripts)
              working-directory: server
              run: npm ci
            - name: Run tests (root)
              working-directory: server
              env:
                PORT: 0
                REDIS_HOST: localhost
                REDIS_PORT: 6379
                REDIS_PASSWORD: test
              run: npm test